### ISSUE TITLE
fft_vs_geom_movie.py example

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#1029]
This example crashes in v2.0.1 using this command line suggested in the docstring:
```
python fft_vs_geom_movie.py --diam 8.36 --obscuration 0.61 --sigma 0.0 --nlayers 6 --size 3.0
```
The problem seems to be with having `sigma = 0`, since changing this to a small value works.

The traceback is:
```
Adding layer at altitude  0.00 km with velocity ( 0.08, -4.13) m/s, and r0_500 0.255 m.
Adding layer at altitude  3.09 km with velocity ( 6.61, -6.62) m/s, and r0_500 0.618 m.
Adding layer at altitude  6.18 km with velocity ( 0.86, 16.40) m/s, and r0_500 1.300 m.
Adding layer at altitude  9.28 km with velocity ( 0.28,  1.58) m/s, and r0_500 1.365 m.
Adding layer at altitude 12.37 km with velocity (10.01,  9.02) m/s, and r0_500 0.979 m.
Adding layer at altitude 15.46 km with velocity (-8.78, -16.90) m/s, and r0_500 1.945 m.
Instantiating screens
|==============================================================================================================|  12 / 12  (100.00%)        34s
Drawing PSFs
|>-------------------------------------------------------------------------------------------------------------|   0 /100  ( 0.00%)
Traceback (most recent call last):
  File "fft_vs_geom_movie.py", line 459, in <module>
    make_movie(args)
  File "fft_vs_geom_movie.py", line 232, in make_movie
    rng=rng)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/gsobject.py", line 1650, in drawImage
    orig_center, local_wcs)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/gsobject.py", line 2135, in drawPhot
    photons = self.shoot(thisN, ud)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/gsobject.py", line 2185, in shoot
    self._shoot(photons, ud)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/utilities.py", line 1427, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/transform.py", line 494, in _shoot
    self._original._shoot(photons, ud)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/utilities.py", line 1427, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/phase_psf.py", line 1476, in _shoot
    photons.x, photons.y = self._screen_list._wavefront_gradient(u, v, t, self.theta)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/phase_psf.py", line 922, in _wavefront_gradient
    gx, gy = layer._wavefront_gradient(u, v, t, theta)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/phase_screens.py", line 779, in _wavefront_gradient
    gradx, grady = self._zernike.evalCartesianGrad(u, v)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/zernike.py", line 494, in evalCartesianGrad
    return self.gradX.evalCartesian(x, y), self.gradY.evalCartesian(x, y)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/utilities.py", line 1395, in __get__
    value = self.fget(obj)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/zernike.py", line 451, in gradX
    _noll_coef_array_gradx(j, self.R_inner/self.R_outer).dot(self.coef[1:])
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/utilities.py", line 965, in __call__
    result = self.user_function(*key)
  File "/Users/david/anaconda3/envs/DESI/lib/python3.6/site-packages/galsim/zernike.py", line 303, in __noll_coef_array_gradx
    _noll_coef_array_xy(jgrad, obscuration).reshape(-1, jgrad),
ValueError: cannot reshape array of size 0 into shape (0)
```

**Comment by jmeyers314** [comment]
Thanks @dkirkby .  I think I may have already fixed this via 7a1386ec .  Is this failure on master or a release branch?

**Comment by dkirkby** [comment]
This is v2.0.1

**Comment by jmeyers314** [comment]
Thanks, I can confirm this crashes on 2.1.4 also.

Using a tiny value for sigma should do the right thing (be nearly equivalent to sigma=0).  So I think this probably doesn't warrant a bugfix release.  Maybe we should add a statement to the CHANGELOG on master though.

**Comment by rmjarvis** [comment]
I just (re-)confirmed that this is already fixed on master, so this will appear in version 2.2.

@jmeyers314 I added an item to this effect in the CHANGLOG in your current PR for #1047.  Please look it over to make sure you agree with the wording.
