### ISSUE TITLE
Sandbox issue with installation on macOS 10.14+

### ISSUE THREAD

**Issue by demitri** [GalSim-developers/GalSim#1035]
Recent macOS releases are restricting access to certain system directories. This prevents GalSim from being installed from source with `python setup.py build` or via `pip install galsim`. (For the record, `conda install -c conda-forge galsim` does work.)

Though poking around, this may not strictly be a macOS issue - as a Mac programmer I have to deal with the Mac Sandbox, which this may or may not be.

This is the output:

```
% python setup.py build
Using setuptools version 41.0.1
Python version =  3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Adding eigency to build_dep
GalSim version is 2.1.5
Compiling eigency/conversions.pyx because it changed.
Compiling eigency/core.pyx because it changed.
[1/2] Cythonizing eigency/conversions.pyx
/usr/local/anaconda/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/yp/lf1xdvp165n5xb7hcrwzpngc0000gn/T/easy_install-9i_ctei3/eigency-1.77/eigency/conversions.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[2/2] Cythonizing eigency/core.pyx
/usr/local/anaconda/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/yp/lf1xdvp165n5xb7hcrwzpngc0000gn/T/easy_install-9i_ctei3/eigency-1.77/eigency/core.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: no files found matching 'eigency/*.pyd'
warning: no previously-included files matching 'CMakeLists.txt' found under directory 'eigency/eigen_3.2.8/Eigen'
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/anaconda/lib/python3.7/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/command/build_py.py", line 53, in run
    self.build_package_data()
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/command/build_py.py", line 121, in build_package_data
    self.mkpath(os.path.dirname(target))
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 338, in mkpath
    dir_util.mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/local/anaconda/lib/python3.7/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/sandbox.py", line 310, in wrap
    path = self._remap_input(name, path, *args, **kw)
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/sandbox.py", line 452, in _remap_input
    self._violation(operation, os.path.realpath(path), *args, **kw)
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/sandbox.py", line 407, in _violation
    raise SandboxViolation(operation, args, kw)
setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('/private/var/var', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by rmjarvis** [comment]
I believe the normal solution to this is
```
pip install -r requirements.txt
python setup.py build  # or install, etc.
```
Does this work for you?

**Comment by demitri** [comment]
It did, thanks. So nothing to do with macOS. Perhaps a note on the home page? I consider myself an advanced Python user and had never come across this before.

**Comment by rmjarvis** [comment]
I'm pretty sure it is related to Mac's (relatively recent) SIP thing.  Pip wants to be able to write into temporary directories to install dependencies, and Mac no longer likes programs doing that.  But installing the dependencies first on their own terms works.

**Comment by rmjarvis** [comment]
I added a link to this issue in the [FAQ item](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)#setup-script-exited-with-error-sandboxviolation) about this potential problem.  Closing.
