### ISSUE TITLE
Boost-related nosetest failures

### ISSUE THREAD

**Issue by reikonakajima** [GalSim-developers/GalSim#309]
Nosetests failed on a Ubuntu-Linux system, and it seems to be related to getting the correct boost library, after the recent updates on the master node.  Any help appreciated!

```
Starting python tests...
EEEEEEEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_GSObject.py", line 10, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_Image.py", line 38, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_SBProfile.py", line 13, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_atmosphere.py", line 11, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_config_gsobject.py", line 11, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_config_value.py", line 12, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_hsm.py", line 20, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_integ.py", line 12, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: NameError (name 'sys' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_lensing.py", line 8, in <module>
    sys.path.append(os.path.abspath(os.path.join(path, "..")))
NameError: name 'sys' is not defined

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_optics.py", line 10, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_random.py", line 10, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_real.py", line 11, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_shear.py", line 11, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_spline.py", line 18, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

======================================================================
ERROR: Failure: ImportError (/export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/reiko/2code/GalSim/tests/test_utilities.py", line 10, in <module>
    import galsim
  File "/export/home/reiko/2code/GalSim/galsim/__init__.py", line 1, in <module>
    from ._galsim import *
ImportError: /export/home/reiko/2code/GalSim/galsim/_galsim.so: undefined symbol: _ZTIN5boost6python15instance_holderE

----------------------------------------------------------------------
Ran 15 tests in 0.005s

FAILED (errors=15)
Nosetests returned error code  1
```

**Comment by dannygoldstein** [comment]
`/bin/rm -r .scon*` fixed a very similar problem for me too. 

Danny
