### ISSUE TITLE
Let galsim.fits.read be more forgiving of bad FITS files

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#602]
When reading some DES images, I got an error trying to use `im = galsim.fits.read(file_name)`.

It turns out that some of the header items have bad values: NAN.0, which means that astropy (or pyfits) chokes on it:
```
>>> f[1].data
WARNING: AstropyDeprecationWarning: The key function is deprecated and may be removed in a future version.
        Use the `.keyword` attribute instead. [astropy.utils.misc]
ERROR: VerifyError: Unparsable card (G-MEANX), fix it first with .verify('fix'). [astropy.io.fits.card]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/astro/SL64/packages/astropy/0.3.1/lib/python2.7/site-packages/astropy-0.3.1-py2.7-linux-x86_64.egg/astropy/utils/misc.py", line 279, in __get__
    val = self._fget(obj)
 ... [snip] ...
  File "/opt/astro/SL64/packages/astropy/0.3.1/lib/python2.7/site-packages/astropy-0.3.1-py2.7-linux-x86_64.egg/astropy/io/fits/card.py", line 543, in value
    self._value = self._parse_value()
  File "/opt/astro/SL64/packages/astropy/0.3.1/lib/python2.7/site-packages/astropy-0.3.1-py2.7-linux-x86_64.egg/astropy/io/fits/card.py", line 975, in _parse_value
    ".verify('fix')." % self.key)
astropy.io.fits.verify.VerifyError: Unparsable card (G-MEANX), fix it first with .verify('fix').
```

Fortunately, it turns out that the recommended action of doing `f[1].verify('fix')` did work:
```
>>> f[1].verify('fix')
WARNING: VerifyWarning: Output verification result: [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 80: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MEANX' is not FITS standard (invalid value string: NAN.0 / [arcsec] Guider x-axis mean offset).  Fixed 'G-MEANX' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 81: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MEANY' is not FITS standard (invalid value string: NAN.0 / [arcsec] Guider y-axis mean offset).  Fixed 'G-MEANY' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 89: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MEANXY' is not FITS standard (invalid value string: NAN.0 / [arcsec2] Guider (xy) 2nd moment mean offset).  Fixed 'G-MEANXY' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 102: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MAXX' is not FITS standard (invalid value string: NAN.0 / [arcsec] Guider x-axis maximum offset).  Fixed 'G-MAXX' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 129: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MEANY2' is not FITS standard (invalid value string: NAN.0 / [arcsec2] Guider (y) 2nd moment mean offset).  Fixed 'G-MEANY2' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 142: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MAXY' is not FITS standard (invalid value string: NAN.0 / [arcsec] Guider y-axis maximum offset).  Fixed 'G-MAXY' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 143: [astropy.io.fits.verify]
WARNING: VerifyWarning:     Card 'G-MEANX2' is not FITS standard (invalid value string: NAN.0 / [arcsec2] Guider (x) 2nd moment mean offset).  Fixed 'G-MEANX2' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Note: Astropy uses zero-based indexing.
 [astropy.io.fits.verify]
>>> f[1].data
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)
```

So I propose that we add a try/catch block around the place in GalSim where we access the data and if the normal version fails, try to do the `verify('fix')` trick and repeat.

My workaround in the meanwhile is to do this myself and then pass GalSim the fixed up HDUList in the  `hdu_list` parameter that we helpfully have in lieu of the `file_name` parameter.  But it would be nice if GalSim did this on its own.

**Comment by rmjarvis** [comment]
This is done on #654.
