### ISSUE TITLE
build test failure

### ISSUE THREAD

**Issue by beckermr** [GalSim-developers/GalSim#678]
So it appears that when using the fits reader from astropy, the test suite for galsim has a failure.

```======================================================================
ERROR: Test the PyAstWCS class
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/beckermr_admin/Desktop/galsim_install/src/GalSim-1.3.0/tests/test_wcs.py", line 1613, in test_pyastwcs
    wcs = galsim.PyAstWCS(file_name, dir=dir)
  File "/usr/local/lib/python2.7/site-packages/galsim/fitswcs.py", line 434, in __init__
    wcsinfo = self._load_from_header(header, hdu)
  File "/usr/local/lib/python2.7/site-packages/galsim/fitswcs.py", line 476, in _load_from_header
    fc = starlink.Ast.FitsChan(starlink.Atl.PyFITSAdapter(hdu))
  File "/usr/local/lib/python2.7/site-packages/starlink/Atl.py", line 106, in __init__
    self.pyfits_3_1_0 = ( LooseVersion(pyfits.__version__) >=
AttributeError: 'module' object has no attribute '__version__'
```

It turns out this is not a failure of galsim, but actually of starlink, since this library is asking for the `__version__` attribute which is not set for the latest pyfits version in astropy. I don't know if galsim needs to do anything about this. Should this be marked as a known failure?

**Comment by rmjarvis** [comment]
Thanks for posting this Matt.  This wasn't a problem with previous versions of starlink.  I've posted an issue on their site [here](https://github.com/timj/starlink-pyast/issues/7).

**Comment by beckermr** [comment]
OK. With the latest starlink-pyast that was just pushed to pypi (3.8.0) the test suite passes just fine. I am closing this issue.
