### ISSUE TITLE
checksum failure for galsim cosmos download?

### ISSUE THREAD

**Issue by beckermr** [GalSim-developers/GalSim#705]
I keep getting this error

```
beckermr@ki-ls07 $ galsim_download_cosmos -v 3 -f 
Downloading from url:
  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_23.5_training_sample.tar.gz
Target location is:
  /u/ki/beckermr/.local/share/galsim/COSMOS_23.5_training_sample.tar.gz

Meta information about url:
Date: Tue, 26 Jan 2016 21:13:42 GMT
Server: Apache/2.2.15 (Scientific Linux)
Last-Modified: Thu, 14 Jan 2016 10:47:44 GMT
ETag: "d5d5-10754aeff-5294904470e00"
Content-Length: 4417957631
Connection: close
Content-Type: text/plain; charset=UTF-8


Size of COSMOS_23.5_training_sample.tar.gz: 4213 MBytes

Target file has already been downloaded and unpacked.  Forced re-download.

Download complete.6 / 4213 MBytes  [25.54%]
Unpacking the tarball...
-rwxr-xr-x rmandelb/staff          0 2016-01-12 19:26:50 COSMOS_23.5_training_sample/
-rw-r--r-- rmandelb/staff      57600 2016-01-12 19:24:47 COSMOS_23.5_training_sample/acs_I_unrot_sci_20_cf.fits
-rw-r--r-- rmandelb/staff       6036 2016-01-12 19:26:01 COSMOS_23.5_training_sample/README
-rw-r--r-- rmandelb/staff    9371520 2016-01-08 08:51:32 COSMOS_23.5_training_sample/real_galaxy_catalog_23.5.fits
-rw-r--r-- rmandelb/staff   14808960 2016-01-08 08:51:32 COSMOS_23.5_training_sample/real_galaxy_catalog_23.5_fits.fits
-rw-r--r-- rmandelb/staff    2473920 2015-12-31 09:52:02 COSMOS_23.5_training_sample/real_galaxy_galsim_selection.fits
-rw-r--r-- rmandelb/staff   74802240 2016-01-08 08:52:02 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n1.fits
-rw-r--r-- rmandelb/staff   74275200 2016-01-08 08:52:02 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n10.fits
-rw-r--r-- rmandelb/staff   82048320 2016-01-08 08:52:02 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n11.fits
-rw-r--r-- rmandelb/staff   78563520 2016-01-08 08:52:03 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n12.fits
-rw-r--r-- rmandelb/staff   69001920 2016-01-08 08:52:03 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n13.fits
-rw-r--r-- rmandelb/staff   75925440 2016-01-08 08:52:03 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n14.fits
-rw-r--r-- rmandelb/staff   80389440 2016-01-08 08:52:03 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n15.fits
-rw-r--r-- rmandelb/staff   69546240 2016-01-08 08:52:03 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n16.fits
-rw-r--r-- rmandelb/staff   73143360 2016-01-08 08:52:04 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n17.fits
-rw-r--r-- rmandelb/staff   73054080 2016-01-08 08:52:04 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n18.fits
-rw-r--r-- rmandelb/staff   69073920 2016-01-08 08:52:04 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n19.fits
-rw-r--r-- rmandelb/staff   69212160 2016-01-08 08:52:05 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n2.fits
-rw-r--r-- rmandelb/staff   68351040 2016-01-08 08:52:05 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n20.fits
-rw-r--r-- rmandelb/staff   70672320 2016-01-08 08:52:05 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n21.fits
-rw-r--r-- rmandelb/staff   68149440 2016-01-08 08:52:05 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n22.fits
-rw-r--r-- rmandelb/staff   72515520 2016-01-08 08:52:05 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n23.fits
-rw-r--r-- rmandelb/staff   77783040 2016-01-08 08:52:06 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n24.fits
-rw-r--r-- rmandelb/staff   68618880 2016-01-08 08:52:06 COSMOS_23.5_training_sample/real_galaxy_images_23.5_n25.fits
Traceback (most recent call last):
  File "/u/ki/beckermr/.local/bin/galsim_download_cosmos", line 258, in <module>
    main()
  File "/u/ki/beckermr/.local/bin/galsim_download_cosmos", line 247, in main
    tar.list(verbose=True)
  File "/opt/TWWfsw/python27/lib/python2.7/tarfile.py", line 1918, in list
    for tarinfo in self:
  File "/opt/TWWfsw/python27/lib/python2.7/tarfile.py", line 2470, in next
    tarinfo = self.tarfile.next()
  File "/opt/TWWfsw/python27/lib/python2.7/tarfile.py", line 2319, in next
    self.fileobj.seek(self.offset)
  File "/opt/TWWfsw/python27/lib/python2.7/gzip.py", line 425, in seek
    self.read(1024)
  File "/opt/TWWfsw/python27/lib/python2.7/gzip.py", line 252, in read
    self._read(readsize)
  File "/opt/TWWfsw/python27/lib/python2.7/gzip.py", line 299, in _read
    self._read_eof()
  File "/opt/TWWfsw/python27/lib/python2.7/gzip.py", line 338, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xb871bced != 0xc566d8d1L
```

**Comment by rmandelb** [comment]
Hmmm, I've never seen that before.  One thing I notice is that the list of files is incomplete - you only seem to go up to n25 in the images, and there are no PSF image files listed (unless you just didn't copy the rest when you were copying the output to paste it here?).  On a probably related note, I notice it says "Download complete.6 / 4213 MBytes  [25.54%]" whereas when I run that command on the cluster here, it says "Download complete.3 / 4213 MBytes  [100.00%]", lists all files, and gives no errors at all.

I wonder if there was an issue with the network connection either on your side or on the server that was just a fluke and is now resolved?  I think you really weren't getting the whole file for some reason.

**Comment by rmjarvis** [comment]
I also wasn't able to reproduce this.  I tried a few different computers, and they were all able to download it completely, except for one where I hit the disk quota (and it gave an error message about this, not what you got where it tried to unpack an incomplete tarball).  Matt, is this still happening for you?

**Comment by beckermr** [comment]
I just moved a copy from another machine. Trying again now.

**Comment by beckermr** [comment]
It is working now. Thanks!

**Comment by rmjarvis** [comment]
OK.  Good.  I'm guessing maybe you tried to download it while Joe was still uploading the new version.  Bad timing.  :)

**Comment by rmjarvis** [comment]
Update: (unrelated to the error Matt reported, but prompted by my investigation of it)

On branch #693, I added an option to galsim_download_cosmos to download the tarball to some other directory (specified by the user with a -d command-line option) and symlink it from the share/galsim directory.  This lets it work on systems that have a modest home directory quota, including the one I mentioned above where I hit my disk quota trying to test it.

On that system, I can now do:
```
$ galsim_download_cosmos -d ~/work
Type galsim_download_cosmos -h to see command line options.
Downloading from url:
  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_23.5_training_sample.tar.gz
Target location is:
  /astro/u/mjarvis/work/COSMOS_23.5_training_sample.tar.gz

Size of COSMOS_23.5_training_sample.tar.gz: 4213 MBytes

Download complete.3 / 4213 MBytes  [100.00%]
Unpacking the tarball...
COSMOS_23.5_training_sample/
[...]
COSMOS_23.5_training_sample/real_galaxy_PSF_images_23.5_n9.fits
Extracted contents of tar file.
Removing the tarball to save space
Made link to /astro/u/mjarvis/work/COSMOS_23.5_training_sample from /astro/u/mjarvis/share/galsim/COSMOS_23.5_training_sample
$ ls -l ~/share/galsim/COSMOS*
lrwxrwxrwx 1 mjarvis 49 Jan 28 23:54 /astro/u/mjarvis/share/galsim/COSMOS_23.5_training_sample -> /astro/u/mjarvis/work/COSMOS_23.5_training_sample/
$ ls -ld ~/work/COSMOS*
drwxr-xr-x 2 mjarvis 262144 Jan 12 22:26 /astro/u/mjarvis/work/COSMOS_23.5_training_sample/
```
And no more disk quote error.  :)

**Comment by rmandelb** [comment]
Nice.  I was wishing for that when I tested it myself.
