### ISSUE TITLE
bug in correlated noise in config

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#732]
When I try to use COSMOSNoise, and set the `file_name` attribute, I was getting an exception that I didn't understand.  To try to track this down, I modified demo1.yaml so that the image.noise now looks like this:

```
    noise : 
        type : COSMOS
        variance: 900
        file_name: my_correlation.fits
```

I think this is legitimate use of image.noise, but here is the exception that gets thrown:

```
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 840, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 427, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 229, in BuildImage
    image = builder.buildImage(cfg_image, config, image_num, obj_num, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 423, in buildImage
    base, obj_num=obj_num, xsize=xsize, ysize=ysize, do_noise=True, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 395, in BuildStamp
    im, current_var = builder.addNoise(stamp,config,im,skip,current_var,logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 836, in addNoise
    current_var = galsim.config.AddNoise(base,image,current_var,logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/noise.py", line 92, in AddNoise
    var = builder.addNoise(noise, config, im, rng, current_var, draw_method, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/noise.py", line 548, in addNoise
    cn = self.getCOSMOSNoise(config,base,rng)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/noise.py", line 540, in getCOSMOSNoise
    cn = galsim.correlatednoise.getCOSMOSNoise(rng, **kwargs)
TypeError: getCOSMOSNoise() got multiple values for keyword argument 'file_name'
```

**Comment by rmandelb** [comment]
Oh, I think it's because in galsim/config/noise.py, there is this line:
```
cn = galsim.correlatednoise.getCOSMOSNoise(rng, **kwargs)
```
which wants to pass the rng first, but getCOSMOSNoise expects file_name first (it doesn't take rng as an unnamed argument any more).

**Comment by rmandelb** [comment]
Will fix and make a PR.

**Comment by rmjarvis** [comment]
Yes.  Thanks.  I guess we don't use this in any of the examples currently, so we didn't notice.

**Comment by rmandelb** [comment]
Yeah, I noticed when I tried to make some sims for HSC using a noise correlation function corresponding to what we see on our coadds.

**Comment by rmandelb** [comment]
Closing #732.
