### ISSUE TITLE
make config failures more helpful?

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#773]
Hi @rmjarvis - I was wondering about making some failures from the config functionality more helpful.  In particular, I had a case just now here I told it to make PSFs from an input file with a name blah.fits.gz which (oops) didn't exist.  The error message was

```
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 840, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 427, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 232, in BuildImage
    image, current_var = builder.buildImage(cfg_image, config, image_num, obj_num, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image_tiled.py", line 157, in buildImage
    xsize=self.stamp_xsize, ysize=self.stamp_ysize, do_noise=self.do_noise_in_stamps)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 104, in BuildStamps
    except_func = except_func)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 840, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 317, in BuildStamp
    logger=logger)[0]
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/gsobject.py", line 186, in BuildGSObject
    gsobject, safe = _BuildSimple(param, base, ignore, gsparams, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/gsobject.py", line 268, in _BuildSimple
    return init_func(**kwargs), safe
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/interpolatedimage.py", line 270, in __init__
    image = galsim.fits.read(image, hdu=hdu)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/fits.py", line 792, in read
    hdu_list, fin = _read_file(file_name, dir, file_compress)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/fits.py", line 203, in __call__
    raise RuntimeError("None of the options for gunzipping were successful.")
RuntimeError: None of the options for gunzipping were successful.
```

It seems to me that it would be helpful if it could (a) recognize that the file doesn't exist at all and/or (b) say what file it couldn't unzip.  (If you have a config file that reads in multiple input files, you won't really know what's going on from this.)  What do you think?

**Comment by rmjarvis** [comment]
I'm always in favor of improved error messaging. :)

In this case, I think it probably points to improving the error message in `galsim.fits.read` rather than something specific to the config layer.  I added a bit to the read function (on master; cf fb7fcf2) so now this is the behavior:
```
>>> im = galsim.fits.read('blah.fits.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/galsim/fits.py", line 797, in read
    hdu_list, fin = _read_file(file_name, dir, file_compress)
  File "/Library/Python/2.7/site-packages/galsim/fits.py", line 200, in __call__
    with open(file) as fid: pass
IOError: [Errno 2] No such file or directory: 'blah.fits.gz'
```
I think that's a good error message for this.  Let me know if you think this is sufficient.

**Comment by rmandelb** [comment]
I'm happy with this.  Thanks!

Closing #773.
