### ISSUE TITLE
python3 run_all_tests

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#783]
I got the following errors when running tests/run_all_tests under python 3.5:

python3 test_wcs.py:
```
ZPX  file_name =  zpx.fits
FitsWCS is really  <class 'galsim.fitswcs.AstropyWCS'>
Start reference testing for FitsWCS ZPX
Start testing celestial WCS FitsWCS zpx.fits
Try pickling  galsim.AstropyWCS('fits_files/zpx.fits', origin=galsim.PositionD(x=0.0, y=0.0))
Start image tests for WCS FitsWCS_ZPX
Traceback (most recent call last):
  File "test_wcs.py", line 1771, in <module>
    test_fitswcs()
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "test_wcs.py", line 1723, in test_fitswcs
    do_wcs_image(wcs, 'FitsWCS_'+tag, approx)
  File "test_wcs.py", line 275, in do_wcs_image
    im2 = galsim.fits.read(test_name, dir=dir)
  File "/Users/josh/src/GalSim/galsim/fits.py", line 802, in read
    wcs, origin = galsim.wcs.readFromFitsHeader(hdu.header)
  File "/Users/josh/src/GalSim/galsim/wcs.py", line 611, in readFromFitsHeader
    wcs = wcs_type._readHeader(header)
  File "/Users/josh/src/GalSim/galsim/fitswcs.py", line 337, in _readHeader
    return AstropyWCS(header=header)
  File "/Users/josh/src/GalSim/galsim/fitswcs.py", line 140, in __init__
    wcs = self._load_from_header(header, hdu)
  File "/Users/josh/src/GalSim/galsim/fitswcs.py", line 183, in _load_from_header
    wcs = astropy.wcs.WCS(header)
  File "/usr/local/lib/python3.5/site-packages/astropy/wcs/wcs.py", line 503, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2213 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 665 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in watset() at line 2788 of file cextern/wcslib/C/dis.c:
Unrecognized field name for WAT (ZPX) on axis 1: DQ1.DOCORR.

zsh: segmentation fault  python3 test_wcs.py
```

python3 test_wfirst.py:
```
Traceback (most recent call last):
  File "test_wfirst.py", line 534, in <module>
    test_wfirst_psfs()
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "test_wfirst.py", line 462, in test_wfirst_psfs
    list(new_dict.keys()), bp_list, err_msg='Wrong list of bandpasses in stored file')
  File "/usr/local/lib/python3.5/site-packages/numpy/testing/utils.py", line 807, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python3.5/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
Wrong list of bandpasses in stored file
(mismatch 100.0%)
 x: array([b'Y106'], 
      dtype='|S7')
 y: array(['Y106'], 
      dtype='<U4')
```

**Comment by jmeyers314** [comment]
Actually, I see that "python test_wcs.py" (i.e., python 2.7) crashes too.

**Comment by rmjarvis** [comment]
> zsh: segmentation fault  python3 test_wcs.py

This one is an astropy bug, not something on our end.  Astropy thinks it can handle ZPX files, but in fact it can't, and sometimes seg faults when trying.  So FitsWCS thinks it succeeds with astropy rather than either dropping through to wcstools or failing and skipping that test.  (If you had PyAst installed, this would have worked, since they implement it correctly, btw.  And that check comes before AstropyWCS.)

I'd thought they fixed this in version 1.2, but apparently not.  So I changed a check I had put in there about this to use version < '999' rather than version < '1.2' and a TODO reminding us to revisit this down the road in case astropy actually fixes this bug.  6ce84309178110f256b753c8ab769059d474d6e9

**Comment by rmjarvis** [comment]
> Wrong list of bandpasses in stored file

This is a typical byte string vs unicode issue that I missed in #534.  Fixed.  c52675b
