### ISSUE TITLE
problem with GREAT3-like example scripts

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#803]
With the current version of GalSim on the master branch, the GREAT3-like example scripts don't seem to run.  For example, with ```cgc.yaml```, it quickly starts spitting out many instances of the following:
```
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 735, in worker
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 429, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 233, in BuildImage
    image, current_var = builder.buildImage(cfg_image, config, image_num, obj_num, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image_tiled.py", line 157, in buildImage
    xsize=self.stamp_xsize, ysize=self.stamp_ysize, do_noise=self.do_noise_in_stamps)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 104, in BuildStamps
    except_func = except_func)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 843, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 387, in BuildStamp
    galsim.config.ProcessExtraOutputsForStamp(config, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/extra.py", line 128, in ProcessExtraOutputsForStamp
    builder.processStamp(obj_num, field, config, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/extra_truth.py", line 73, in processStamp
    value = galsim.config.ParseValue(cols,name,base,None)[0]
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/value.py", line 148, in ParseValue
    val_safe = generate_func(param, base, value_type)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/value_eval.py", line 90, in _GenerateFromEval
    keys = np.unique(keys).tolist()
NameError: global name 'np' is not defined
```
This sounds related to one of the issues Erin brought up recently that I thought was fixed.

```cgc_psf.yaml``` has a different problem:
```
Traceback (most recent call last):
  File "/usr/local/bin/galsim", line 288, in <module>
    main()
  File "/usr/local/bin/galsim", line 275, in main
    galsim.config.Process(config, logger, njobs=args.njobs, job=args.job, new_params=new_params)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 610, in Process
    UpdateConfig(config, new_params)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 527, in UpdateConfig
    SetInConfig(config, key, value)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 510, in SetInConfig
    config, key = ParseExtendedKey(config, key)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 480, in ParseExtendedKey
    d = d[k]
KeyError: 'input'
```

I just checked and found I get the same error on releases/1.4 for ```cgc_psf.yaml```, but ```cgc.yaml``` seems fine on there.

Other than fixing the issues (and perhaps on releases/1.4 as well), I was wondering if we can/should have this as part of our default testing... e.g., should ```check_yaml``` run these scripts?

**Comment by rmjarvis** [comment]
Sorry, I discovered that and fixed it on branch #580, so if we're happy with that, we can just merge that.  Or add `import numpy as np` at the top of `galsim/config/value_eval.py`.

**Comment by rmandelb** [comment]
I just went to #580 and confirm that cgc.yaml is fine, but ```cgc_psf.yaml``` still has the same error as in the initial post.

Also, re the fix on #580 for cgc.yaml, my two other questions remain: (1) can/should we do this on releases/1.4 so that our next bug-fix version has a working cgc.yaml, and (2) do you agree about putting this into ```check_yaml``` or doing something else to make sure these scripts continue to get checked regularly to ensure that they work?  (I guess we could just update the PR checklist to include these scripts explicitly, but is there any downside to having them run in ```check_yaml``` so that all demos get checked at once?)

**Comment by rmjarvis** [comment]
I haven't been able to reproduce the problem with `cgc_psf.yaml`.  On master or releases/1.4.  And I only get the cgc.yaml problem on master, not releases/1.4.  (The bug in value_eval.py wasn't present yet in releases/1.4.)  So I don't know what is going on to give you this error in cgc_psf.yaml.

> do you agree about putting this into check_yaml or doing something else to make sure these scripts continue to get checked regularly to ensure that they work?

I did add them to the Travis checks on #580 as part of run_examples.py.  That's when I found the bug and fixed it.

**Comment by rmjarvis** [comment]
Looking at the traceback for the cgc_psf.yaml error, it looks like it's applying a command-line (or post-template) modification to the config dict.  Something that starts with `input.`.  Are you maybe running this with some extra command line options?

If so, we can work to improve the error message for this, since the existing one is not overly informative.

**Comment by rmandelb** [comment]
Ahhh, OK, I had copy-pasted a line that made a command-line modification to the config dict for the input catalog (so that cgc.yaml would run with my COSMOSCatalog in a non-default location), and just replaced ```cgc.yaml``` with ```cgc_psf.yaml```.  So yes, that must be it!  Sorry.  Improvements to this error message would be helpful. 

Just to clarify:
> And I only get the cgc.yaml problem on master, not releases/1.4. 

The same is true with me, so I think there is no inconsistency.

**Comment by rmjarvis** [comment]
> Improvements to this error message would be helpful.

I added something on branch '#580':
```
$ galsim cgc_psf.yaml output.nfiles=1 input.cosmos_catalog.sample=25.2
Using config file cgc_psf.yaml
Traceback (most recent call last):
  File "/Users/Mike/bin/galsim", line 260, in <module>
    main()
  File "/Users/Mike/bin/galsim", line 247, in main
    galsim.config.Process(config, logger, njobs=args.njobs, job=args.job, new_params=new_params)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 628, in Process
    UpdateConfig(config, new_params)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 545, in UpdateConfig
    SetInConfig(config, key, value)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 528, in SetInConfig
    config, key = ParseExtendedKey(config, key)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 497, in ParseExtendedKey
    raise ValueError("Unable to parse extended key %s.  Field %s is invalid."%(key,k))
ValueError: Unable to parse extended key input.cosmos_catalog.sample.  Field input is invalid.
$ galsim cgc_psf.yaml output.nfiles=1 psf.ellip.e.max=0.1
Using config file cgc_psf.yaml
Traceback (most recent call last):
  File "/Users/Mike/bin/galsim", line 260, in <module>
    main()
  File "/Users/Mike/bin/galsim", line 247, in main
    galsim.config.Process(config, logger, njobs=args.njobs, job=args.job, new_params=new_params)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 628, in Process
    UpdateConfig(config, new_params)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 545, in UpdateConfig
    SetInConfig(config, key, value)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 528, in SetInConfig
    config, key = ParseExtendedKey(config, key)
  File "/Library/Python/2.7/site-packages/galsim/config/process.py", line 497, in ParseExtendedKey
    raise ValueError("Unable to parse extended key %s.  Field %s is invalid."%(key,k))
ValueError: Unable to parse extended key psf.ellip.e.max.  Field ellip is invalid.
```

**Comment by rmandelb** [comment]
Great.  This eliminates the mystery errors.
