### ISSUE TITLE
ERROR: Test the PyAstWCS class

### ISSUE THREAD

**Issue by PFLeget** [GalSim-developers/GalSim#850]
Hi, 

I am installing GalSim for the firs time and when I am running all the test, I have just one error which looks like : 
```
=====================================================================
ERROR: Test the PyAstWCS class
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/Leget 1/GalSim/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "/Users/Leget 1/GalSim/tests/test_wcs.py", line 1568, in test_pyastwcs
    wcs = galsim.PyAstWCS(file_name, dir=dir)
  File "/sw/lib/python2.7/site-packages/galsim/fitswcs.py", line 456, in __init__
    wcsinfo = self._load_from_header(header, hdu)
  File "/sw/lib/python2.7/site-packages/galsim/fitswcs.py", line 497, in _load_from_header
    wcsinfo = fc.read()
BDFTS: astPutFits(FitsChan): Illegal keyword value supplied.
astPutFits(FitsChan): Unable to store the following FITS header card:
EXPTIME =              420.000 / Exposure time (sec)                            

-------------------- >> begin captured stdout << ---------------------
ZPX  file_name =  zpx.fits

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 394 tests in 80.590s

FAILED (SKIP=19, errors=1)
Nosetests returned error code  1
scons: *** [tests/tests.log] Explicit exit, status 1
scons: building terminated because of errors.
```
Do you have any ideas where it could work ? 

Thanks a lot

**Comment by rmjarvis** [comment]
Do you have the latest version of starlink-pyast?  (3.9.0 I believe)
```
pip install -U starlink-pyast
```

**Comment by rmjarvis** [comment]
@PFLeget Just checking in on this, since I never heard back from you.  Is this still an issue for you?  If so, can you provide more information about your system.  Especially that starlink version you have installed and maybe how you installed it (pip or otherwise).

**Comment by PFLeget** [comment]
Hi, 

This is not an issue anymore. I just re-install everything with last version, and now this is working. 

Thanks a lot

**Comment by rmjarvis** [comment]
OK.  Thanks for the update.
