### ISSUE TITLE
test_sensor failures on master

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#883]
I'm getting the following failures when running the test suite on master, both on macOS 10.12.4 (py2 and py3) and RHEL 6.9 (py2).

```
======================================================================
FAIL: test_sensor.test_sensor_wavelengths_and_angles
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/lsstsw/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josh/src/GalSimPy2/tests/galsim_test_helpers.py", line 542, in f2
    result = f(*args, **kwargs)
  File "/Users/josh/src/GalSimPy2/tests/test_sensor.py", line 395, in test_sensor_wavelengths_and_angles
    assert r4 > r1
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Starting test_wavelengths_and_angles
Testing Wavelength and Angle sampling - i band
Flux = 3539:                sum        peak          radius
No lamb, no angles:         3503.0     435.00       0.309004
W/ lamb, no angles:         3502.0     435.00       0.308952
No lamb, w/ angles:         3503.0     429.00       0.308881
W/ lamb, w/ angles:         3503.0     408.00       0.320105
check r4 > r1 due to added wavelengths and angles
r1 = 0.309004, r4 = 0.320105, 2*sigma_r = 0.010086
Testing Wavelength and Angle sampling - i band
Flux = 3539:                sum        peak          radius
No lamb, no angles:         -1.1     0.00       0.066448
W/ lamb, no angles:         -1.1     0.00       0.066417
No lamb, w/ angles:         -1.1     0.00       0.066201
W/ lamb, w/ angles:         -1.1     0.00       0.065832
check r4 > r1 due to added wavelengths and angles
r1 = 0.066448, r4 = 0.065832, 2*sigma_r = 0.010086

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test that drawing with method='fft' also works for SiliconSensor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/lsstsw/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/josh/src/GalSimPy2/tests/galsim_test_helpers.py", line 542, in f2
    result = f(*args, **kwargs)
  File "/Users/josh/src/GalSimPy2/tests/test_sensor.py", line 254, in test_silicon_fft
    np.testing.assert_almost_equal(im2.array, im3.array, decimal=5)
  File "/Users/josh/src/lsstsw/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 523, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/josh/src/lsstsw/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/Users/josh/src/lsstsw/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

(mismatch 5.6640625%)
 x: array([[  0.00000e+00,   0.00000e+00,  -1.56431e-12, ...,  -1.56336e-12,
          0.00000e+00,   0.00000e+00],
       [  0.00000e+00,   0.00000e+00,  -1.02410e-12, ...,  -1.02341e-12,...
 y: array([[  2.16889e-12,   7.41211e-13,  -2.07745e-12, ...,  -2.08171e-12,
          7.35441e-13,   2.16434e-12],
       [  7.33509e-13,   2.49063e-13,  -7.06510e-13, ...,  -7.06465e-13,...
-------------------- >> begin captured stdout << ---------------------
New, saved array sizes:  (64, 64) (64, 64)
Sum of values:  -0.00579805116179 -0.00578630663775
Minimum image value:  -8.31406699504e-05 -8.31406699504e-05
Maximum image value:  0.0 0.0
Peak location:  0 0
Moments Mx, My, Mxx, Myy, Mxy for new array: 
      32.497123        32.439872        140.05413        141.8108         -0.012892624   
Moments Mx, My, Mxx, Myy, Mxy for saved array: 
      32.5             32.5             140.21229        140.21229        3.443765e-09   
Flux = 3539:  sum        peak         radius
im1:         -0.0     0.00       0.004559
im2:         -0.0     0.00       0.004542
im3:         3539.0     412.35       0.312254

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 491 tests in 74.369s

FAILED (SKIP=19, failures=2)
Nosetests returned error code  1
scons: *** [tests/tests.log] Explicit exit, status 1
scons: building terminated because of errors.
```

**Comment by jmeyers314** [comment]
Looks like something isn't working in 
`template <class T> PhotonArray::PhotonArray(const BaseImage<T>& image, double maxFlux, UniformDeviate ud)`

I should have asked this years ago, but how do you turn on the `dbg<< ...` statements in the cpp files?  I don't think I've ever cleanly figured that out.

**Comment by rmjarvis** [comment]
> how do you turn on the dbg<< ... statements in the cpp files?

Just uncomment the line that says
```
#define DEBUGLOGGING
```
This turns on all `dbg<< 'blah'` lines.  Then you can programmatically enable `xdbg<< 'blah'` lines by putting
```
set_verbose(2);
```
before you want them enabled.  If you don't want to be deluged by other xdbg lines elsewhere in the code, you can turn it back off at the end of the function by adding
```
set_verbose(1);
```
at the end.  You can also redirect the debug statements to a file if you want with
```
set_dbgout(new ofstream('debug.out'))
```
but I usually just redirect the output if I want to do something like that.

**Comment by rmjarvis** [comment]
Oh, I think this might be the bug I already fixed on #873.  So before you go too far investigating this, try that branch to see if that fixes things for you.

**Comment by rmjarvis** [comment]
4c13c1e0ca7cc3fd435647be2317d3d564760411

**Comment by jmeyers314** [comment]
Yep.  That was it.  I'll look through that PR now.

**Comment by rmjarvis** [comment]
Do #881 first, so we can cut a release for Jim.
