### ISSUE TITLE
demo13.py: ValueError: numpy.ndarray argument must have contiguous rows

### ISSUE THREAD

**Issue by josePhoenix** [GalSim-developers/GalSim#890]
I just tried to run demo13.py with GalSim from Homebrew (v1.3.0) and got `ValueError: numpy.ndarray argument must have contiguous rows` in `wfirst.getPSF`. Is this a known issue? Should I install `HEAD`/`master`?

```
$ python2 demo13.py
Poisson noise model created.
Reading from a parametric COSMOS catalog.
Read in 98 galaxies from catalog
Doing expensive pre-computation of PSF.
Beginning to loop over SCAs and get the PSF:
   ... SCA 7
Traceback (most recent call last):
  File "demo13.py", line 494, in <module>
    main(sys.argv)
  File "demo13.py", line 143, in main
    PSFs = wfirst.getPSF(SCAs=use_SCA, approximate_struts=True, n_waves=10, logger=logger)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 230, in getPSF
    oversample_fac=1.5)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/chromatic.py", line 226, in interpolate
    return InterpolatedChromaticObject(self, waves, oversample_fac)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/chromatic.py", line 788, in __init__
    objs = [ obj.evaluateAtWavelength(wave) for wave in self.waves ]
  File "/Users/jlong/lib/python2.7/site-packages/galsim/chromatic.py", line 2126, in evaluateAtWavelength
    **self.kwargs)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/optics.py", line 333, in __init__
    pupil_plane_im=pupil_plane_im, pupil_angle=pupil_angle, oversampling=oversampling)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/optics.py", line 938, in psf_image
    im = galsim.Image(array.astype(np.float64), scale=scale)
  File "/Users/jlong/lib/python2.7/site-packages/galsim/image.py", line 321, in __init__
    self.image = _galsim.ImageView[self.dtype](array, xmin, ymin)
ValueError: numpy.ndarray argument must have contiguous rows
```

**Comment by rmjarvis** [comment]
This was related to a change in one of the recent numpy versions.  It's been fixed on master and will be incorporated into v1.5 (which should be pretty soon now).

**Comment by josePhoenix** [comment]
Cheers, thanks!
