### ISSUE TITLE
Opaque raise of bad redshift in sed.withMagnitude()

### ISSUE THREAD

**Issue by matroxel** [GalSim-developers/GalSim#905]
Mike asked to submit example of opaque traceback of impact of weird redshifts on sed.withMagnitude(). Example below, along with raise and traceback. Probably sufficient to add check on valid redshifts in sed.atRedshift().

Example:
sedpath = os.path.join(galsim.meta_data.share_dir, 'SEDs', 'CWW_Sbc_ext.sed')
galaxy_sed = galsim.SED(sedpath, wave_type='Ang', flux_type='flambda')
galaxy_sed = galaxy_sed.atRedshift(-99)
galaxy_sed = galaxy_sed.withMagnitude(22,wfirst.getBandpasses()['F184']) * galsim.wfirst.collecting_area * galsim.wfirst.exptime

Raise:
ValueError: zero-size array to reduction operation minimum which has no identity

Traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 626, in withMagnitude
    current_magnitude = self.calculateMagnitude(bandpass)
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 700, in calculateMagnitude
    flux = self.calculateFlux(bandpass)
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 678, in calculateFlux
    return np.trapz(bandpass(x) * self(x), x)
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 385, in __call__
    return self._call_fast(wave)
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 321, in _call_fast
    self._check_bounds(wave)
  File "/users/PCON0003/cond0083/lib/python2.7/site-packages/galsim/sed.py", line 274, in _check_bounds
    wmin = np.min(wave)
  File "/users/PCON0003/cond0083/.conda/envs/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2397, in amin
    out=out, **kwargs)
  File "/users/PCON0003/cond0083/.conda/envs/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by jmeyers314** [comment]
Hmm...  I didn't bother stepping through to see what failed precisely, but probably raising an exception if z <= -1 is a reasonable solution.

**Comment by rmjarvis** [comment]
The proximate error is when `galsim.utilities.combine_wave_list()` gets two wave lists whose blue-red ranges don't overlap, it happily returns an empty array.  We probably want to raise a more informative error in that case.  

But warning when z < 0 (or z < -1 if you prefer) is also a good idea.

**Comment by jmeyers314** [comment]
Ah, thanks.  I'll add an exception for that case too.

**Comment by rmandelb** [comment]
I'd say z<-0.01 or something like that.  Sometimes you might have a mixed star+galaxy catalog, and the z's for the stars might have some very small negative values corresponding to stellar motions in the MW.  We don't want it to crash in that case.  But -0.01 is larger than stellar motions in the MW, so seems like a safe limit.

**Comment by jmeyers314** [comment]
I agree -0.01 is pretty insanely blueshifted, but I also think it's pretty unlikely that someone would use -0.01 as a sentinel for "bad redshift".  So I think I'm inclined to just stick with 1+z > 0 and let users hurl stars at Earth at whatever (subluminal) speed they like :)

**Comment by jmeyers314** [comment]
Fixed in #907.
