### ISSUE TITLE
compilation issues pre-tagging v1.5

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#920]
I'm having some issues with the latest version of master.

I had not tried out Craig's latest sensor PR, and apparently it is the cause of the issues on my Mac: one test failure in the lookup table tests and another in `test_treerings.py`.  Output below:

```
galsim_test_helpers.py:555: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @timer
    def test_treerings():
        """Test the addition of tree rings.
        compare image positions with the simple sensor to
        a SiliconSensor with no tree rings and six
        different additions of tree rings.
        """
        from scipy import stats
        # Set up the different sensors.
        treering_amplitude = 0.5
        rng1 = galsim.BaseDeviate(5678)
        rng2 = galsim.BaseDeviate(5678)
        rng3 = galsim.BaseDeviate(5678)
        rng4 = galsim.BaseDeviate(5678)
        rng5 = galsim.BaseDeviate(5678)
        rng6 = galsim.BaseDeviate(5678)
        rng7 = galsim.BaseDeviate(5678)
        sensor0 = galsim.Sensor()
        sensor1 = galsim.SiliconSensor(rng=rng1)
        tr2 = galsim.SiliconSensor.simple_treerings(treering_amplitude, 250.)
        sensor2 = galsim.SiliconSensor(rng=rng2, treering_func=tr2,
                                       treering_center=galsim.PositionD(-1000.0,0.0))
        sensor3 = galsim.SiliconSensor(rng=rng3, treering_func=tr2,
                                       treering_center=galsim.PositionD(1000.0,0.0))
        sensor4 = galsim.SiliconSensor(rng=rng4, treering_func=tr2,
                                       treering_center=galsim.PositionD(0.0,-1000.0))
        tr5 = galsim.SiliconSensor.simple_treerings(treering_amplitude, 250., r_max=2000, dr=1.)
        sensor5 = galsim.SiliconSensor(rng=rng5, treering_func=tr5,
                                       treering_center=galsim.PositionD(0.0,1000.0))
    
        # Now test the ability to read in a user-specified function
        tr6 = galsim.LookupTable.from_func(treering_function, x_min=0.0, x_max=2000)
        sensor6 = galsim.SiliconSensor(rng=rng6, treering_func=tr6,
                                       treering_center=galsim.PositionD(-1000.0,0.0))
    
        # Now test the ability to read in a lookup table
        tr7 = galsim.LookupTable.from_file('tree_ring_lookup.dat', amplitude=treering_amplitude)
        sensor7 = galsim.SiliconSensor(rng=rng7, treering_func=tr7,
                                       treering_center=galsim.PositionD(-1000.0,0.0))
    
        sensors = [sensor0, sensor1, sensor2, sensor3, sensor4, sensor5, sensor6, sensor7]
        names = ['Sensor()',
                 'SiliconSensor, no TreeRings',
                 'SiliconSensor, TreeRingCenter= (-1000,0)',
                 'SiliconSensor, TreeRingCenter= (1000,0)',
                 'SiliconSensor, TreeRingCenter= (0,-1000)',
                 'SiliconSensor, TreeRingCenter= (0,1000)',
                 'SiliconSensor with specified function, TreeRingCenter= (-1000,0)',
                 'SiliconSensor with lookup table, TreeRingCenter= (-1000,0)']
        centers = [None, None,
                   (-1000,0),
                   (1000,0),
                   (0,-1000),
                   (0,1000),
                   (-1000,0),
                   (-1000,0)]
    
        init_flux = 200000
        obj = galsim.Gaussian(flux=init_flux, sigma=0.3)
    
        im = galsim.ImageD(10,10, scale=0.3)
        obj.drawImage(im)
        ref_mom = galsim.utilities.unweighted_moments(im)
        print('Reference Moments Mx, My = (%f, %f):'%(ref_mom['Mx'], ref_mom['My']))
    
        for sensor, name, center in zip(sensors, names, centers):
            im = galsim.ImageD(10,10, scale=0.3)
            obj.drawImage(im, method='phot', sensor=sensor)
            mom = galsim.utilities.unweighted_moments(im)
            print('%s, Moments Mx, My = (%f, %f):'%(name, mom['Mx'], mom['My']))
            if center is None:
                np.testing.assert_almost_equal(mom['Mx'], ref_mom['Mx'], decimal = 1)
                np.testing.assert_almost_equal(mom['My'], ref_mom['My'], decimal = 1)
            else:
                np.testing.assert_almost_equal(ref_mom['Mx'] + treering_amplitude * center[0] / 1000,
>                                              mom['Mx'], decimal=1)
E               AssertionError: 
E               Arrays are not almost equal to 1 decimals
E                ACTUAL: 4.9999999999999982
E                DESIRED: 5.0982237619400443

test_sensor.py:637: AssertionError
----------------------------- Captured stdout call -----------------------------
Reference Moments Mx, My = (5.500000, 5.500000):
Sensor(), Moments Mx, My = (5.502504, 5.497211):
SiliconSensor, no TreeRings, Moments Mx, My = (5.495176, 5.501351):
SiliconSensor, TreeRingCenter= (-1000,0), Moments Mx, My = (5.098224, 5.497632):
============== 2 failed, 506 passed, 19 skipped in 114.60 seconds ==============

```

**Comment by rmandelb** [comment]
Sorry, that was only one test failure.  Here's the other:
```
    @timer
    def test_from_func():
        """Test the LookupTable.from_func factory function"""
        x_min = 2
        x_max = 200
    
        # Linear interpolation
        x1 = np.linspace(x_min, x_max, 2000)
        f1 = [x**3 for x in x1]
        tab1 = galsim.LookupTable(x1, f1, interpolant='linear')
        tab2 = galsim.LookupTable.from_func(lambda x:x**3, x_min, x_max, interpolant='linear')
        print('tab1 = ',tab1, tab1(10))
        print('tab2 = ',tab2, tab2(10))
    
        # Spline interpolation
        tab3 = galsim.LookupTable(x1, f1)
        tab4 = galsim.LookupTable.from_func(lambda x:x**3, x_min, x_max)
        print('tab3 = ',tab3, tab3(10))
        print('tab4 = ',tab4, tab4(10))
    
        # Log interpolation
        x5 = np.exp(np.linspace(np.log(x_min), np.log(x_max), 2000))
        f5 = [x**3 for x in x5]
        tab5 = galsim.LookupTable(x5, f5, x_log=True, f_log=True)
        tab6 = galsim.LookupTable.from_func(lambda x:x**3, x_min, x_max, x_log=True, f_log=True)
        print('tab5 = ',tab5, tab5(10))
        print('tab6 = ',tab6, tab6(10))
    
        test_x_vals = [2.641, 39.85, 81.23125]
        for x in test_x_vals:
            truth = x**3
            f1 = tab1(x)
            f2 = tab2(x)
            f3 = tab3(x)
            f4 = tab4(x)
            f5 = tab5(x)
            f6 = tab6(x)
            print(truth, f1, f2, f3, f4, f5, f6)
>           np.testing.assert_almost_equal(f1/truth, 1.0, decimal=3)
E           AssertionError: 
E           Arrays are not almost equal to 3 decimals
E            ACTUAL: 1.0010522675776132
E            DESIRED: 1.0

test_table.py:257: AssertionError
----------------------------- Captured stdout call -----------------------------
tab1 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0], interpolant='linear') 1000.0523997
tab2 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0], interpolant='linear') 1000.0523997
tab3 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0]) 1000.0
tab4 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0]) 1000.0
tab5 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0], x_log=True, f_log=True) 1000.0
tab6 =  galsim.LookupTable(x=[2.0,...,200.0], f=[8.0,...,8000000.0], x_log=True, f_log=True) 1000.0
18.420660721 18.440044185 18.440044185 18.4206627734 18.4206627734 18.420660721 18.420660721
_
```

**Comment by rmjarvis** [comment]
Interesting.  I found a machine that reproduces your error, and it seems to be due to the numpy version being older.
With numpy 1.13, the following works:
```
>>> numpy.testing.assert_almost_equal(1.00105, 1, 3)
```
With numpy 1.11, it doesn't
```
>>> numpy.testing.assert_almost_equal(1.00105, 1, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mjarvis/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 539, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 3 decimals
 ACTUAL: 1.00105
 DESIRED: 1
```
So i guess this is just a matter of reducing the accuracy threshold.

**Comment by rmjarvis** [comment]
Oops.  Actually the sensor one was a bug.  I messed up the formula for the simple cosine tree rings when I ported Craig's code up to python, but it was close enough that it wasn't caught by numpy 1.13's more relaxed test.  So I fixed that.

Both fixes are on master.  If anyone wants to review, the commits are df86052c0f0862bcefb4531b3b42d3375b40519d and e71f2f9eb1ea4fa95cbac6c145bc0767ca566176.

**Comment by rmandelb** [comment]
Interesting!  Thanks, I confirm that fixes it for me.  Closing #920.
