### ISSUE TITLE
galsim.lsst module is broken

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#964]
The galsim.lsst unit tests are skipped if the lsst stack is not setup, which is usually the case when I'm running the galsim unit tests.  I decided recently though to try these tests out again, and found that the stack has apparently evolved significantly since the galsim.lsst module was written.

To start, the lsst.pex.logging package has more or less been removed since Jan '17 (https://jira.lsstcorp.org/browse/RFC-29), and the cameraGeom.PUPIL coordinate system was renamed cameraGeom.FIELD_ANGLE around August '17 (https://community.lsst.org/t/new-camera-geometry-based-on-transform/2188).  These changes prevent the galsim.lsst module from being imported.

After replacing the logger and `PUPIL` -> `FIELD_ANGLE`, the unit tests produce the following errors: 

```
======================================================================
ERROR: test_pupil_coords_from_pixel_coords (__main__.LsstCameraTestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 380, in test_pupil_coords_from_pixel_coords
    self.camera._pixel_coord_from_point_and_name(camera_point_list, chip_name_list)
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 421, in _pixel_coord_from_point_and_name
    cp = self._camera.makeCameraPoint(pt, FIELD_ANGLE)
AttributeError: 'Camera' object has no attribute 'makeCameraPoint'

======================================================================
ERROR: test_rotation_angle_pixel_coordinate_convention (__main__.LsstCameraTestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 482, in test_rotation_angle_pixel_coordinate_convention
    x_0, y_0, name = camera.pixelCoordsFromPoint(pointing)
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 475, in pixelCoordsFromPoint
    xx, yy = self._pixel_coord_from_point_and_name(camera_point_list, chip_name_list)
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 421, in _pixel_coord_from_point_and_name
    cp = self._camera.makeCameraPoint(pt, FIELD_ANGLE)
AttributeError: 'Camera' object has no attribute 'makeCameraPoint'

======================================================================
ERROR: test_pickling (__main__.LsstWcsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 770, in test_pickling
    pickle.dump(self.wcs, output_file)
TypeError: write() argument must be str, not bytes

======================================================================
ERROR: test_round_trip (__main__.LsstWcsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 693, in test_round_trip
    im0.write(outputFile)
  File "/Users/josh/src/GalSim/galsim/fits.py", line 593, in write
    image.wcs.writeToFitsHeader(hdu.header, image.bounds)
  File "/Users/josh/src/GalSim/galsim/wcs.py", line 603, in writeToFitsHeader
    wcs._writeHeader(header, bounds)
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 971, in _writeHeader
    tanSipWcs = self.getTanSipWcs()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 953, in getTanSipWcs
    tanWcs = self.getTanWcs()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 838, in getTanWcs
    xTanPixMin, xTanPixMax, yTanPixMin, yTanPixMax = self._getTanPixelBounds()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 811, in _getTanPixelBounds
    self._detector.makeCameraPoint(cornerPoint, FOCAL_PLANE),
AttributeError: 'lsst.afw.cameraGeom._detector.Detector' object has no attribute 'makeCameraPoint'

======================================================================
ERROR: test_tan_sip_wcs (__main__.LsstWcsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 627, in test_tan_sip_wcs
    tanWcs = self.wcs.getTanWcs()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 838, in getTanWcs
    xTanPixMin, xTanPixMax, yTanPixMin, yTanPixMax = self._getTanPixelBounds()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 811, in _getTanPixelBounds
    self._detector.makeCameraPoint(cornerPoint, FOCAL_PLANE),
AttributeError: 'lsst.afw.cameraGeom._detector.Detector' object has no attribute 'makeCameraPoint'

======================================================================
ERROR: test_tan_wcs (__main__.LsstWcsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 561, in f2
    result = f(*args, **kwargs)
  File "test_lsst.py", line 585, in test_tan_wcs
    tanWcs = self.wcs.getTanWcs()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 838, in getTanWcs
    xTanPixMin, xTanPixMax, yTanPixMin, yTanPixMax = self._getTanPixelBounds()
  File "/Users/josh/src/GalSim/galsim/lsst/lsst_wcs.py", line 811, in _getTanPixelBounds
    self._detector.makeCameraPoint(cornerPoint, FOCAL_PLANE),
AttributeError: 'lsst.afw.cameraGeom._detector.Detector' object has no attribute 'makeCameraPoint'

----------------------------------------------------------------------
```

So it seems to me that no one has been interested in this module since at least Jan '17.  I guess the question is: should we fix it or just kill it?

**Comment by rmjarvis** [comment]
I've always held out hope that we would get something from LSST DM that was actually portable rather than dependent on the LSST stack.  Then people could build an LSST-looking simulation without requiring the stack.  But it appears there is no interest by anyone in making that happen.

I guess unless @danielsf wants to make an effort to update this module, I'd be inclined to just kill this here and point people to imSim for simulations that look like LSST images.  (Which does depend on the stack of course.)

**Comment by danielsf** [comment]
Oh, wow.  Yeah... this is at least two major API changes out of date with where the LSST stack is.

I also thought of this as a stop-gap measure until we could factor out some pure python version of the LSST camera model with minimal dependence on the rest of the LSST stack.  As Mike says, that is not going to happen.  I vote that we kill this module, especially given that ImSim now exists.

**Comment by rmandelb** [comment]
+1

**Comment by rmjarvis** [comment]
I think since this is technically an API change (even though the old API is completely broken), it makes the most sense to do this for v2.0 rather than 1.6.  Any objections to me just doing it directly on the noboost branch?  I don't think there is anything really that needs to be reviewed about this.

**Comment by jmeyers314** [comment]
> Any objections to me just doing it directly on the noboost branch? 

Sounds good to me.

**Comment by rmjarvis** [comment]
Done: fb952c10a6f2ef57dd378928242ec56a051e2c75
